# railway.toml - Configuração para Django

[build]
buildCommand = "pip install --upgrade pip && pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn core.wsgi:application --bind 0.0.0.0:8000"


