# Generated by Django 5.1.1 on 2025-10-09 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id_equip', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('mask', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evento', models.CharField(max_length=15)),
                ('matricula', models.CharField(blank=True, max_length=15, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('equip_id', models.CharField(blank=True, max_length=10, null=True)),
                ('equip_nome', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Refeicao',
            fields=[
                ('id_grup', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=15)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('admissao', models.DateField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('centro_de_custo', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('credencial', models.CharField(blank=True, max_length=50, null=True)),
                ('ativo', models.SlugField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.empresa')),
                ('grup_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.grupo_refeicao')),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_param', models.CharField(max_length=15)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('mod_padrao_usu', models.BooleanField(default=False)),
                ('mod_credito_usu', models.BooleanField(default=False)),
                ('mod_padrao_visi', models.BooleanField(default=False)),
                ('mod_credito_visi', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id_ref', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Inter_grup_ref',
            fields=[
                ('id_inter', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.empresa')),
                ('grup_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.grupo_refeicao')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.refeicao')),
            ],
            options={
                'unique_together': {('grup_ref', 'ref')},
            },
        ),
        migrations.AddField(
            model_name='grupo_refeicao',
            name='refeicoes',
            field=models.ManyToManyField(related_name='grupos', through='website.Inter_grup_ref', to='website.refeicao'),
        ),
        migrations.CreateModel(
            name='Terceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('credencial', models.CharField(blank=True, max_length=50, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.empresa')),
                ('func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.funcionario')),
                ('grup_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.grupo_refeicao')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('permissao', models.CharField(blank=True, max_length=50, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('credencial', models.CharField(blank=True, max_length=50, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=50, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.empresa')),
                ('func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.funcionario')),
                ('grup_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.grupo_refeicao')),
            ],
        ),
    ]
