# Generated by Django 5.1.1 on 2025-10-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_visitante_emp_ter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='emp_ter',
        ),
        migrations.AddField(
            model_name='terceiro',
            name='emp_ter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
