# Generated by Django 5.1.1 on 2025-10-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_visitante_emp_ter_terceiro_emp_ter'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='tipo_pessoa',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='terceiro',
            name='tipo_pessoa',
            field=models.IntegerField(default=3, editable=False),
        ),
        migrations.AddField(
            model_name='visitante',
            name='tipo_pessoa',
            field=models.IntegerField(default=2, editable=False),
        ),
    ]
