# Generated by Django 5.1.1 on 2025-10-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_funcionario_tipo_pessoa_terceiro_tipo_pessoa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo_pessoa',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
