# Generated by Django 5.1.1 on 2025-10-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_evento_tipo_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo_pessoa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
